# Generated by Django 5.0.6 on 2025-05-09 06:08

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(default='fas fa-question-circle', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria de Contato',
                'verbose_name_plural': 'Categorias de Contatos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(default='fas fa-question-circle', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria de Dúvida',
                'verbose_name_plural': 'Categorias de Dúvidas',
            },
        ),
        migrations.CreateModel(
            name='CategoriaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(default='fas fa-question-circle', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria de Ferramenta',
                'verbose_name_plural': 'Categorias de Ferramentas',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem_url', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('avaliacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('tipo', models.CharField(choices=[('CLINICA', 'Clínica'), ('PROFISSIONAL', 'Profissional'), ('ASSOCIACAO', 'Associação'), ('ESCOLA', 'Escola'), ('GRUPO_APOIO', 'Grupo de Apoio'), ('EMERGENCIA', 'Emergência')], max_length=20)),
                ('atendimento_presencial', models.BooleanField(default=True)),
                ('atendimento_online', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.categoriafaq')),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone_classe', models.CharField(default='fas fa-tools', max_length=50)),
                ('eh_gratuita', models.BooleanField(default=False)),
                ('classificacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('categoria', models.CharField(choices=[('pictogramas_escolares', 'Pictogramas Escolares'), ('alfabetizacao', 'Alfabetização'), ('brinquedos_brincadeiras', 'Brinquedos e Brincadeiras'), ('historias_sociais', 'Histórias Sociais'), ('atividades_diversas', 'Atividades Diversas')], max_length=100)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='core.categoriaferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='UserDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_download', models.DateTimeField(auto_now_add=True)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ferramenta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='core.customuser')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-data_download'],
            },
        ),
    ]
