# Generated by Django 5.2.4 on 2025-08-03 20:33

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Contato',
                'verbose_name_plural': 'Categorias de Contatos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Dúvida',
                'verbose_name_plural': 'Categorias de Dúvidas',
            },
        ),
        migrations.CreateModel(
            name='CategoriaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Ferramenta',
                'verbose_name_plural': 'Categorias de Ferramentas',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('rua', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Número com código do país (ex: 5511999999999)', max_length=20, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('atendimento_presencial', models.BooleanField(default=True)),
                ('atendimento_online', models.BooleanField(default=False)),
                ('especialidades', models.TextField(blank=True, help_text='Liste as especialidades separadas por vírgula', null=True)),
                ('convenios', models.TextField(blank=True, help_text='Convênios aceitos', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.categoriacontato')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.categoriafaq')),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone_classe', models.CharField(default='fas fa-tools', max_length=50)),
                ('eh_gratuita', models.BooleanField(default=False)),
                ('classificacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('categoria', models.CharField(choices=[('pictogramas_escolares', 'Pictogramas Escolares'), ('alfabetizacao', 'Alfabetização'), ('brinquedos_brincadeiras', 'Brinquedos e Brincadeiras'), ('historias_sociais', 'Histórias Sociais'), ('atividades_diversas', 'Atividades Diversas')], max_length=100)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='core.categoriaferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='FotoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='static/img/contatos/')),
                ('legenda', models.CharField(blank=True, max_length=200, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.contato')),
            ],
            options={
                'verbose_name': 'Foto do Contato',
                'verbose_name_plural': 'Fotos dos Contatos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='UserDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_download', models.DateTimeField(auto_now_add=True)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ferramenta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='core.customuser')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-data_download'],
            },
        ),
        migrations.CreateModel(
            name='UserSavedContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_salva', models.DateTimeField(auto_now_add=True, verbose_name='Data de Salvamento')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.contato', verbose_name='Contato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_contatos', to='core.customuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Contato Salvo',
                'verbose_name_plural': 'Contatos Salvos',
                'ordering': ['-data_salva'],
                'indexes': [models.Index(fields=['user', '-data_salva'], name='core_usersa_user_id_fadf65_idx'), models.Index(fields=['contato'], name='core_usersa_contato_886516_idx')],
                'unique_together': {('user', 'contato')},
            },
        ),
        migrations.CreateModel(
            name='UserSavedFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_salva', models.DateTimeField(auto_now_add=True, verbose_name='Data de Salvamento')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.faq', verbose_name='Dúvida Frequente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_faqs', to='core.customuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Dúvida Salva',
                'verbose_name_plural': 'Dúvidas Salvas',
                'ordering': ['-data_salva'],
                'indexes': [models.Index(fields=['user', '-data_salva'], name='core_usersa_user_id_b0fbee_idx'), models.Index(fields=['faq'], name='core_usersa_faq_id_0baaca_idx')],
                'unique_together': {('user', 'faq')},
            },
        ),
    ]
