# Generated by Django 5.2.4 on 2025-08-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacontato',
            name='icone',
            field=models.CharField(choices=[('fas fa-book-open', 'Livro Aberto (Definições, Contexto)'), ('fas fa-stethoscope', 'Estetoscópio (Diagnóstico, Tratamento)'), ('fas fa-gavel', 'Martelo (Legislação, Direitos)'), ('fas fa-graduation-cap', 'Chapéu de Formatura (Educação)'), ('fas fa-comment-medical', 'Balão de Fala (Terapias)'), ('fas fa-hands-helping', 'Mãos Ajudando (Apoio, ONGs)'), ('fas fa-clinic-medical', 'Clínica (Clínicas, Hospitais)'), ('fas fa-user-md', 'Médico (Profissionais de Saúde)'), ('fas fa-users', 'Grupo de Pessoas (Grupos de Apoio)'), ('fas fa-building-ngo', 'Prédio (Associações)'), ('fas fa-info-circle', 'Círculo de Informação (Geral)'), ('fas fa-question-circle', 'Círculo de Interrogação (Padrão)'), ('fas fa-tools', 'Ferramentas (Ferramentas)')], default='fas fa-question-circle', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='categoriafaq',
            name='icone',
            field=models.CharField(choices=[('fas fa-book-open', 'Livro Aberto (Definições, Contexto)'), ('fas fa-stethoscope', 'Estetoscópio (Diagnóstico, Tratamento)'), ('fas fa-gavel', 'Martelo (Legislação, Direitos)'), ('fas fa-graduation-cap', 'Chapéu de Formatura (Educação)'), ('fas fa-comment-medical', 'Balão de Fala (Terapias)'), ('fas fa-hands-helping', 'Mãos Ajudando (Apoio, ONGs)'), ('fas fa-clinic-medical', 'Clínica (Clínicas, Hospitais)'), ('fas fa-user-md', 'Médico (Profissionais de Saúde)'), ('fas fa-users', 'Grupo de Pessoas (Grupos de Apoio)'), ('fas fa-building-ngo', 'Prédio (Associações)'), ('fas fa-info-circle', 'Círculo de Informação (Geral)'), ('fas fa-question-circle', 'Círculo de Interrogação (Padrão)'), ('fas fa-tools', 'Ferramentas (Ferramentas)')], default='fas fa-question-circle', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='categoriaferramenta',
            name='icone',
            field=models.CharField(choices=[('fas fa-book-open', 'Livro Aberto (Definições, Contexto)'), ('fas fa-stethoscope', 'Estetoscópio (Diagnóstico, Tratamento)'), ('fas fa-gavel', 'Martelo (Legislação, Direitos)'), ('fas fa-graduation-cap', 'Chapéu de Formatura (Educação)'), ('fas fa-comment-medical', 'Balão de Fala (Terapias)'), ('fas fa-hands-helping', 'Mãos Ajudando (Apoio, ONGs)'), ('fas fa-clinic-medical', 'Clínica (Clínicas, Hospitais)'), ('fas fa-user-md', 'Médico (Profissionais de Saúde)'), ('fas fa-users', 'Grupo de Pessoas (Grupos de Apoio)'), ('fas fa-building-ngo', 'Prédio (Associações)'), ('fas fa-info-circle', 'Círculo de Informação (Geral)'), ('fas fa-question-circle', 'Círculo de Interrogação (Padrão)'), ('fas fa-tools', 'Ferramentas (Ferramentas)')], default='fas fa-question-circle', max_length=50, verbose_name='Ícone'),
        ),
    ]
