# Generated by Django 5.2.4 on 2025-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacontato',
            name='icone',
            field=models.CharField(choices=[('fas fa-info-circle', 'Círculo de Informação'), ('fas fa-question-circle', 'Círculo de Interrogação (Padrão)'), ('fas fa-tools', 'Ferramentas'), ('fas fa-star', 'Estrela'), ('fas fa-heart', 'Coração'), ('fas fa-tag', 'Etiqueta'), ('fas fa-bell', 'Sino'), ('fas fa-bookmark', 'Marca-página'), ('fas fa-user', 'Usuário (Individual)'), ('fas fa-users', 'Grupo de Pessoas (Grupos de Apoio)'), ('fas fa-user-md', 'Médico (Profissionais de Saúde)'), ('fas fa-user-graduate', 'Chapéu de Formatura (Educação)'), ('fas fa-hands-helping', 'Mãos Ajudando (Apoio, ONGs)'), ('fas fa-child', 'Criança'), ('fas fa-stethoscope', 'Estetoscópio (Diagnóstico, Tratamento)'), ('fas fa-clinic-medical', 'Clínica (Clínicas, Hospitais)'), ('fas fa-brain', 'Cérebro (Saúde Mental, Neurologia)'), ('fas fa-comments', 'Balão de Fala (Terapias)'), ('fas fa-puzzle-piece', 'Peça de Quebra-cabeça (Autismo)'), ('fas fa-capsules', 'Cápsulas (Medicação)'), ('fas fa-gavel', 'Martelo (Legislação, Direitos)'), ('fas fa-book-open', 'Livro Aberto (Definições, Contexto)'), ('fas fa-school', 'Escola (Educação)'), ('fas fa-balance-scale', 'Balança da Justiça (Direitos)'), ('fas fa-building', 'Prédio (Associações)'), ('fas fa-home', 'Casa (Apoio Familiar)'), ('fas fa-hospital', 'Hospital'), ('fas fa-phone', 'Telefone'), ('fas fa-envelope', 'Envelope (Email)'), ('fas fa-map-marker-alt', 'Marcador de Mapa (Localização)'), ('fas fa-link', 'Link (Recursos Online)'), ('fas fa-search', 'Lupa (Pesquisa)')], default='fas fa-question-circle', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='categoriafaq',
            name='icone',
            field=models.CharField(choices=[('fas fa-info-circle', 'Círculo de Informação'), ('fas fa-question-circle', 'Círculo de Interrogação (Padrão)'), ('fas fa-tools', 'Ferramentas'), ('fas fa-star', 'Estrela'), ('fas fa-heart', 'Coração'), ('fas fa-tag', 'Etiqueta'), ('fas fa-bell', 'Sino'), ('fas fa-bookmark', 'Marca-página'), ('fas fa-user', 'Usuário (Individual)'), ('fas fa-users', 'Grupo de Pessoas (Grupos de Apoio)'), ('fas fa-user-md', 'Médico (Profissionais de Saúde)'), ('fas fa-user-graduate', 'Chapéu de Formatura (Educação)'), ('fas fa-hands-helping', 'Mãos Ajudando (Apoio, ONGs)'), ('fas fa-child', 'Criança'), ('fas fa-stethoscope', 'Estetoscópio (Diagnóstico, Tratamento)'), ('fas fa-clinic-medical', 'Clínica (Clínicas, Hospitais)'), ('fas fa-brain', 'Cérebro (Saúde Mental, Neurologia)'), ('fas fa-comments', 'Balão de Fala (Terapias)'), ('fas fa-puzzle-piece', 'Peça de Quebra-cabeça (Autismo)'), ('fas fa-capsules', 'Cápsulas (Medicação)'), ('fas fa-gavel', 'Martelo (Legislação, Direitos)'), ('fas fa-book-open', 'Livro Aberto (Definições, Contexto)'), ('fas fa-school', 'Escola (Educação)'), ('fas fa-balance-scale', 'Balança da Justiça (Direitos)'), ('fas fa-building', 'Prédio (Associações)'), ('fas fa-home', 'Casa (Apoio Familiar)'), ('fas fa-hospital', 'Hospital'), ('fas fa-phone', 'Telefone'), ('fas fa-envelope', 'Envelope (Email)'), ('fas fa-map-marker-alt', 'Marcador de Mapa (Localização)'), ('fas fa-link', 'Link (Recursos Online)'), ('fas fa-search', 'Lupa (Pesquisa)')], default='fas fa-question-circle', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='categoriaferramenta',
            name='icone',
            field=models.CharField(choices=[('fas fa-info-circle', 'Círculo de Informação'), ('fas fa-question-circle', 'Círculo de Interrogação (Padrão)'), ('fas fa-tools', 'Ferramentas'), ('fas fa-star', 'Estrela'), ('fas fa-heart', 'Coração'), ('fas fa-tag', 'Etiqueta'), ('fas fa-bell', 'Sino'), ('fas fa-bookmark', 'Marca-página'), ('fas fa-user', 'Usuário (Individual)'), ('fas fa-users', 'Grupo de Pessoas (Grupos de Apoio)'), ('fas fa-user-md', 'Médico (Profissionais de Saúde)'), ('fas fa-user-graduate', 'Chapéu de Formatura (Educação)'), ('fas fa-hands-helping', 'Mãos Ajudando (Apoio, ONGs)'), ('fas fa-child', 'Criança'), ('fas fa-stethoscope', 'Estetoscópio (Diagnóstico, Tratamento)'), ('fas fa-clinic-medical', 'Clínica (Clínicas, Hospitais)'), ('fas fa-brain', 'Cérebro (Saúde Mental, Neurologia)'), ('fas fa-comments', 'Balão de Fala (Terapias)'), ('fas fa-puzzle-piece', 'Peça de Quebra-cabeça (Autismo)'), ('fas fa-capsules', 'Cápsulas (Medicação)'), ('fas fa-gavel', 'Martelo (Legislação, Direitos)'), ('fas fa-book-open', 'Livro Aberto (Definições, Contexto)'), ('fas fa-school', 'Escola (Educação)'), ('fas fa-balance-scale', 'Balança da Justiça (Direitos)'), ('fas fa-building', 'Prédio (Associações)'), ('fas fa-home', 'Casa (Apoio Familiar)'), ('fas fa-hospital', 'Hospital'), ('fas fa-phone', 'Telefone'), ('fas fa-envelope', 'Envelope (Email)'), ('fas fa-map-marker-alt', 'Marcador de Mapa (Localização)'), ('fas fa-link', 'Link (Recursos Online)'), ('fas fa-search', 'Lupa (Pesquisa)')], default='fas fa-question-circle', max_length=50, verbose_name='Ícone'),
        ),
    ]
