# Generated by Django 5.0.6 on 2025-05-10 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='tipo',
        ),
        migrations.AddField(
            model_name='contato',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.categoriacontato'),
        ),
        migrations.AlterField(
            model_name='categoriacontato',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoriafaq',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoriaferramenta',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
