# Generated by Django 5.2.4 on 2025-10-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoriacontato_icone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='aprovado',
            field=models.BooleanField(default=True, verbose_name='Aprovado para exibição'),
        ),
    ]
