# Generated by Django 5.2.4 on 2025-08-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoriacontato_icone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='imagem',
        ),
        migrations.AddField(
            model_name='contato',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL da Imagem'),
        ),
    ]
