# Generated by Django 5.0.6 on 2025-05-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contato_tipo_contato_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='avaliacao',
        ),
    ]
