# Generated by Django 5.0.6 on 2025-05-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contato_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='contato',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='contatos/'),
        ),
        migrations.AddField(
            model_name='contato',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
