# Generated by Django 5.2.4 on 2025-10-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contato_aprovado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='endereço de e-mail'),
        ),
    ]
