# Generated by Django 5.2.4 on 2025-08-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contato_imagem_contato_imagem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotocontato',
            name='imagem',
        ),
        migrations.AddField(
            model_name='fotocontato',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL da Imagem'),
        ),
    ]
