# Generated by Django 5.0.6 on 2025-05-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contato_imagem_url_contato_bairro_contato_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
