# Generated by Django 5.2.4 on 2025-08-17 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_fotocontato_imagem_fotocontato_imagem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo do Aluno')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('nivel_autismo', models.IntegerField(blank=True, choices=[(1, 'Nível 1 - Exige apoio'), (2, 'Nível 2 - Exige apoio substancial'), (3, 'Nível 3 - Exige apoio muito substancial')], null=True, verbose_name='Nível de Suporte (Autismo)')),
                ('laudo', models.FileField(blank=True, null=True, upload_to='laudos_alunos/', verbose_name='Laudo (PDF ou Imagem)')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Turma')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_professor',
            field=models.BooleanField(default=False, verbose_name='É professor?'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='apenas_para_professores',
            field=models.BooleanField(default=False, verbose_name='Apenas para professores?'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='O arquivo PDF da ferramenta para download.', null=True, upload_to='ferramentas_pdfs/', verbose_name='Arquivo PDF'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='autor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Autor/Fonte'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='habilidades_desenvolvidas',
            field=models.CharField(blank=True, help_text='Ex: Comunicação, Interação Social, Coordenação Motora', max_length=255, null=True, verbose_name='Habilidades Desenvolvidas'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Imagem que aparecerá no card da ferramenta.', null=True, upload_to='ferramentas_capas/', verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='publico_alvo',
            field=models.CharField(blank=True, choices=[('pais_familiares', 'Pais e Familiares'), ('professores', 'Professores'), ('terapeutas', 'Terapeutas'), ('criancas_jovens', 'Crianças e Jovens'), ('todos', 'Todos os Públicos')], max_length=50, null=True, verbose_name='Público-Alvo'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='core.categoriaferramenta'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='classificacao',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Classificação (0.0 a 5.0)'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='eh_gratuita',
            field=models.BooleanField(default=True, verbose_name='É Gratuita?'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='icone_classe',
            field=models.CharField(default='fas fa-tools', max_length=50, verbose_name='Ícone (Classe Font Awesome)'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome da Ferramenta'),
        ),
        migrations.CreateModel(
            name='RelatorioDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Relatório')),
                ('relato', models.TextField(verbose_name='Relato de Desempenho')),
                ('data_relatorio', models.DateTimeField(auto_now_add=True, verbose_name='Data do Relatório')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='core.aluno', verbose_name='Aluno')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_criados', to='core.customuser', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Relatório de Desempenho',
                'verbose_name_plural': 'Relatórios de Desempenho',
                'ordering': ['-data_relatorio'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.turma', verbose_name='Turma Regular'),
        ),
    ]
