# Generated by Django 5.2.4 on 2025-08-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aluno_turma_remove_ferramenta_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='laudo',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='arquivo_pdf',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='imagem_capa',
        ),
        migrations.AddField(
            model_name='aluno',
            name='laudo_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Laudo (URL do Arquivo)'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='arquivo_pdf_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL do Arquivo PDF'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='imagem_capa_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL da Imagem de Capa'),
        ),
    ]
