# Generated by Django 5.0.6 on 2025-06-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contato_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_salva', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_faqs', to='core.customuser')),
            ],
            options={
                'verbose_name': 'Dúvida Salva',
                'verbose_name_plural': 'Dúvidas Salvas',
                'ordering': ['-data_salva'],
                'unique_together': {('user', 'faq')},
            },
        ),
    ]
