# Generated by Django 5.2.4 on 2025-09-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_aluno_laudo_remove_ferramenta_arquivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='fonte',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Fonte'),
        ),
    ]
