# Generated by Django 5.0.6 on 2025-06-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersavedfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedfaq',
            name='data_salva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Salvamento'),
        ),
        migrations.AlterField(
            model_name='usersavedfaq',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.faq', verbose_name='Dúvida Frequente'),
        ),
        migrations.AlterField(
            model_name='usersavedfaq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_faqs', to='core.customuser', verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='usersavedfaq',
            index=models.Index(fields=['user', '-data_salva'], name='core_usersa_user_id_b0fbee_idx'),
        ),
        migrations.AddIndex(
            model_name='usersavedfaq',
            index=models.Index(fields=['faq'], name='core_usersa_faq_id_0baaca_idx'),
        ),
    ]
