# Generated by Django 5.0.6 on 2025-06-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usersavedfaq_data_salva_alter_usersavedfaq_faq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='convenios',
            field=models.TextField(blank=True, help_text='Convênios aceitos', null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='especialidades',
            field=models.TextField(blank=True, help_text='Liste as especialidades separadas por vírgula', null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número com código do país (ex: 5511999999999)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FotoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='static/img/contatos/')),
                ('legenda', models.CharField(blank=True, max_length=200, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.contato')),
            ],
            options={
                'verbose_name': 'Foto do Contato',
                'verbose_name_plural': 'Fotos dos Contatos',
                'ordering': ['ordem'],
            },
        ),
    ]
