# Generated by Django 5.0.6 on 2025-06-14 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contato_convenios_contato_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_salva', models.DateTimeField(auto_now_add=True, verbose_name='Data de Salvamento')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.contato', verbose_name='Contato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_contatos', to='core.customuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Contato Salvo',
                'verbose_name_plural': 'Contatos Salvos',
                'ordering': ['-data_salva'],
                'indexes': [models.Index(fields=['user', '-data_salva'], name='core_usersa_user_id_fadf65_idx'), models.Index(fields=['contato'], name='core_usersa_contato_886516_idx')],
                'unique_together': {('user', 'contato')},
            },
        ),
    ]
